[pytest]
testpaths = 
    tests/unit 
    tests/integration

norecursedirs = tests/setup .pytest_cache __pycache__

python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short